### ISSUE TITLE
Opera GX にて Works ページを閲覧した際に、「15 Puzzle」の表示が崩れています

### ISSUE THREAD

**Issue by Assault-8448** [mii-community/mii.community#1]
Opera GX ( Version: LVL2 73.0.3856.396 ) にて、 https://mii.community/works/ を閲覧した際、
15 Puzzle の枠 (flex) の表示が崩れています。

![image](https://user-images.githubusercontent.com/34514603/107883879-f7203e00-6f34-11eb-8a5b-51b74f83104e.png)

**Comment by HiraginoYuki** [comment]
おぺらgxがわるいやろWW

**Comment by Assault-8448** [comment]
おい

**Comment by Assault-8448** [comment]
進捗どうですか？？？ｗ

**Comment by tenzyu** [comment]
原因わからんぽ〜〜〜＞＜

**Comment by Assault-8448** [comment]
＞＜

**Comment by Assault-8448** [comment]
進捗どうですか

**Comment by HiraginoYuki** [comment]
無礼
せめて手がかりになりそうな物でも持ってきたらどうだ

**Comment by Assault-8448** [comment]
多分Opera GXのバグでした　すみませんでした

（現環境にて再現不可能　GXのバグでないとしたら環境問題）

**Comment by HiraginoYuki** [comment]
了解
俺も試してみます

**Comment by HiraginoYuki** [comment]
こちらも再現不可能
Closeしたほうがいいかも

**Comment by Assault-8448** [comment]
了解です　ありがとうございます
